import { ArrowRight, BookOpenText, Check, Clock3, Copy, MessageSquareQuote, Sparkles } from 'lucide-react'
import type { Example, ModelOption, Term, Translation } from './api'

export function ModelSelector({ models, value, onChange, loading }: {
  models: ModelOption[]; value: string; onChange: (value: string) => void; loading: boolean
}) {
  return <div className="flex flex-wrap items-center gap-3">
    <label htmlFor="model" className="eyebrow !mb-0">Translation method</label>
    <select id="model" className="model-select" value={value} onChange={event => onChange(event.target.value)} disabled={loading}>
      {models.filter(option => option.available).map(option =>
        <option value={option.id} key={option.id}>{option.label}</option>
      )}
    </select>
  </div>
}

export function TranslationPanel({ text, onTextChange, onTranslate, loading, disabled }: {
  text: string; onTextChange: (value: string) => void; onTranslate: () => void;
  loading: boolean; disabled: boolean
}) {
  return <section className="editor-card">
    <div className="editor-heading">
      <div className="flex items-center gap-3"><span className="language-mark">Hr</span><div><p className="eyebrow">SOURCE LANGUAGE</p><h2>H’rê</h2></div></div>
      <span className="mini-tag">INPUT</span>
    </div>
    <textarea aria-label="H’rê input" className="editor-input" placeholder="Type or paste H’rê text here…" value={text} onChange={event => onTextChange(event.target.value)} maxLength={2000} />
    <div className="editor-footer">
      <span className="character-count">{text.length} / 2,000 characters</span>
      <button className="translate-button" type="button" onClick={onTranslate} disabled={loading || disabled || !text.trim()}>
        {loading ? <><span className="spinner" /> Translating</> : <>Translate <ArrowRight size={18} strokeWidth={2.2} /></>}
      </button>
    </div>
  </section>
}

export function TranslationResult({ result, loading, copied, onCopy }: {
  result: Translation | null; loading: boolean; copied: boolean; onCopy: () => void
}) {
  return <section className="editor-card result-card">
    <div className="editor-heading">
      <div className="flex items-center gap-3"><span className="language-mark output-mark">Vi</span><div><p className="eyebrow">TARGET LANGUAGE</p><h2>Vietnamese</h2></div></div>
      <span className="mini-tag output-tag">OUTPUT</span>
    </div>
    <div className={`output-area ${!result ? 'empty-output' : ''}`} aria-live="polite">
      {loading ? <div className="status-content"><span className="spinner dark" /> Working on your translation…</div> :
        result ? <p className="translated-text">{result.translation || 'No translation returned.'}</p> :
        <div className="empty-illustration"><Sparkles size={26} strokeWidth={1.4} /><p>Your translation will appear here.</p><span>Choose a method, then press Translate.</span></div>}
    </div>
    <div className="editor-footer result-footer">
      <span className="character-count">{result ? `Generated by ${result.model.replaceAll('_', ' ')}` : 'Ready when you are'}</span>
      <button type="button" className="copy-button" onClick={onCopy} disabled={!result?.translation} aria-label="Copy translation">
        {copied ? <Check size={17} /> : <Copy size={17} />} {copied ? 'Copied' : 'Copy'}
      </button>
    </div>
  </section>
}

export function MetricCard({ icon, label, value, detail }: {
  icon: React.ReactNode; label: string; value: string; detail: string
}) {
  return <div className="metric-card"><span className="metric-icon">{icon}</span><div><p className="eyebrow">{label}</p><strong>{value}</strong><small>{detail}</small></div></div>
}

export function ResultMetrics({ result }: { result: Translation }) {
  return <div className="metrics-grid">
    <MetricCard icon={<Sparkles size={19} />} label="MODEL USED" value={result.model.replaceAll('_', ' ')} detail="Selected inference route" />
    <MetricCard icon={<Clock3 size={19} />} label="RESPONSE TIME" value={`${Math.round(result.latency_ms).toLocaleString()} ms`} detail="Measured by the API" />
    <MetricCard icon={<BookOpenText size={19} />} label="RETRIEVAL" value={result.similarity == null ? '—' : `${Math.round(result.similarity * 100)}%`} detail={result.similarity == null ? 'Not used for this method' : 'Top example similarity'} />
  </div>
}

export function RetrievedTerms({ terms }: { terms: Term[] }) {
  return <section className="context-card"><div className="context-heading"><span className="context-icon"><BookOpenText size={18} /></span><div><h3>Dictionary matches</h3><p>Terms found in your source text</p></div><span className="count-pill">{terms.length}</span></div>
    {terms.length ? <div className="term-list">{terms.map((term, index) => <div className="term-row" key={`${term.source}-${index}`}><span>{term.source || '—'}</span><ArrowRight size={15} /><strong>{term.target || '—'}</strong></div>)}</div> : <div className="context-empty">No dictionary matches for this translation.</div>}
  </section>
}

export function RetrievedExamples({ examples }: { examples: Example[] }) {
  return <section className="context-card"><div className="context-heading"><span className="context-icon"><MessageSquareQuote size={18} /></span><div><h3>Similar examples</h3><p>From the training-only translation memory</p></div><span className="count-pill">{examples.length}</span></div>
    {examples.length ? <div className="example-list">{examples.slice(0, 3).map((example, index) => <div className="example-item" key={`${example.source}-${index}`}><div className="flex items-center justify-between gap-4"><span className="eyebrow">EXAMPLE {String(index + 1).padStart(2, '0')}</span>{example.similarity != null && <span className="similarity">{Math.round(example.similarity * 100)}% match</span>}</div><p>{example.source || '—'}</p><span>{example.target || '—'}</span></div>)}</div> : <div className="context-empty">This method did not retrieve any sentence examples.</div>}
  </section>
}
